-- ========================================
-- SEED DES PERMISSIONS SYSTÈME RBAC (POSTGRESQL)
-- Nettoyage + normalisation complète (4 rôles cibles)
-- ========================================

CREATE TEMP TABLE desired_permissions (
  code VARCHAR(255) PRIMARY KEY,
  label JSONB,
  "group" VARCHAR(255),
  description JSONB
);

INSERT INTO desired_permissions (code, label, "group", description) VALUES
('accesses.assign', '{"fr": "Assigner des rôles", "en": "Assign roles"}'::jsonb, 'accesses', '{"fr": "Permet d''assigner plusieurs rôles à un utilisateur", "en": "Allows assigning multiple roles to a user"}'::jsonb),
('accesses.create', '{"fr": "Créer des accès", "en": "Create accesses"}'::jsonb, 'accesses', '{"fr": "Permet de créer de nouvelles associations utilisateur-rôle", "en": "Allows creating new user-role associations"}'::jsonb),
('accesses.delete', '{"fr": "Supprimer les accès", "en": "Delete accesses"}'::jsonb, 'accesses', '{"fr": "Permet de supprimer (soft delete) les associations utilisateur-rôle", "en": "Allows soft deleting user-role associations"}'::jsonb),
('accesses.hard_delete', '{"fr": "Supprimer définitivement les accès", "en": "Hard delete accesses"}'::jsonb, 'accesses', '{"fr": "Permet de supprimer définitivement les associations utilisateur-rôle", "en": "Allows hard deleting user-role associations"}'::jsonb),
('accesses.read', '{"fr": "Lire les accès", "en": "Read accesses"}'::jsonb, 'accesses', '{"fr": "Permet de lire les associations utilisateur-rôle", "en": "Allows reading user-role associations"}'::jsonb),
('accesses.remove', '{"fr": "Retirer des rôles", "en": "Remove roles"}'::jsonb, 'accesses', '{"fr": "Permet de retirer plusieurs rôles d''un utilisateur", "en": "Allows removing multiple roles from a user"}'::jsonb),
('accesses.update', '{"fr": "Mettre à jour les accès", "en": "Update accesses"}'::jsonb, 'accesses', '{"fr": "Permet de modifier les associations utilisateur-rôle existantes", "en": "Allows modifying existing user-role associations"}'::jsonb),
('admin.access', '{"en":"admin.access","fr":"admin.access"}'::jsonb, 'admin', NULL),
('admin.activity.read', '{"en":"admin.activity.read","fr":"admin.activity.read"}'::jsonb, 'admin', NULL),
('admin.analytics.events', '{"en":"admin.analytics.events","fr":"admin.analytics.events"}'::jsonb, 'admin', NULL),
('admin.analytics.revenue', '{"en":"admin.analytics.revenue","fr":"admin.analytics.revenue"}'::jsonb, 'admin', NULL),
('admin.backup.create', '{"en":"admin.backup.create","fr":"admin.backup.create"}'::jsonb, 'admin', NULL),
('admin.dashboard.read', '{"fr": "Dashboard admin", "en": "Dashboard admin"}'::jsonb, 'admin', '{"fr": "Voir le tableau de bord administrateur", "en": "View administrator dashboard"}'::jsonb),
('admin.designers.read', '{"en":"admin.designers.read","fr":"admin.designers.read"}'::jsonb, 'admin', NULL),
('admin.events.read', '{"en":"admin.events.read","fr":"admin.events.read"}'::jsonb, 'admin', NULL),
('admin.export', '{"en":"admin.export","fr":"admin.export"}'::jsonb, 'admin', NULL),
('admin.health.read', '{"fr": "Health admin", "en": "Health admin"}'::jsonb, 'admin', '{"fr": "Voir les health checks administrateur", "en": "View administrator health checks"}'::jsonb),
('admin.logs.create', '{"en":"admin.logs.create","fr":"admin.logs.create"}'::jsonb, 'admin', NULL),
('admin.logs.read', '{"en":"admin.logs.read","fr":"admin.logs.read"}'::jsonb, 'admin', NULL),
('admin.metrics.read', '{"fr": "Metrics admin", "en": "Metrics admin"}'::jsonb, 'admin', '{"fr": "Voir les métriques administrateur", "en": "View administrator metrics"}'::jsonb),
('admin.metrics.reset', '{"fr": "Reset metrics admin", "en": "Reset metrics admin"}'::jsonb, 'admin', '{"fr": "Réinitialiser les métriques administrateur", "en": "Reset administrator metrics"}'::jsonb),
('admin.moderate', '{"en":"admin.moderate","fr":"admin.moderate"}'::jsonb, 'admin', NULL),
('admin.security.read', '{"fr": "Security admin", "en": "Security admin"}'::jsonb, 'admin', '{"fr": "Voir les informations de sécurité administrateur", "en": "View administrator security information"}'::jsonb),
('admin.stats.read', '{"en":"admin.stats.read","fr":"admin.stats.read"}'::jsonb, 'admin', NULL),
('admin.templates.read', '{"en":"admin.templates.read","fr":"admin.templates.read"}'::jsonb, 'admin', NULL),
('admin.users.read', '{"en":"admin.users.read","fr":"admin.users.read"}'::jsonb, 'admin', NULL),
('admin.wallet.transfer', '{"fr": "Transférer portefeuille admin", "en": "Admin wallet transfer"}'::jsonb, 'admin', '{"fr": "Effectuer des transferts administratifs de portefeuille", "en": "Perform administrative wallet transfers"}'::jsonb),
('authorizations.cache', '{"fr": "Gérer le cache d''autorisations", "en": "Manage authorization cache"}'::jsonb, 'authorizations', '{"fr": "Permet de gérer le cache des autorisations utilisateur", "en": "Allows managing user authorization cache"}'::jsonb),
('authorizations.check', '{"fr": "Vérifier les autorisations", "en": "Check authorizations"}'::jsonb, 'authorizations', '{"fr": "Permet de vérifier les permissions d''un utilisateur", "en": "Allows checking user permissions"}'::jsonb),
('authorizations.create', '{"fr": "Créer des autorisations", "en": "Create authorizations"}'::jsonb, 'authorizations', '{"fr": "Permet de créer de nouvelles associations rôle-permission-menu", "en": "Allows creating new role-permission-menu associations"}'::jsonb),
('authorizations.delete', '{"fr": "Supprimer les autorisations", "en": "Delete authorizations"}'::jsonb, 'authorizations', '{"fr": "Permet de supprimer (soft delete) les associations rôle-permission-menu", "en": "Allows soft deleting role-permission-menu associations"}'::jsonb),
('authorizations.hard_delete', '{"fr": "Supprimer définitivement les autorisations", "en": "Hard delete authorizations"}'::jsonb, 'authorizations', '{"fr": "Permet de supprimer définitivement les associations rôle-permission-menu", "en": "Allows hard deleting role-permission-menu associations"}'::jsonb),
('authorizations.manage', '{"en":"authorizations.manage","fr":"authorizations.manage"}'::jsonb, 'authorizations', NULL),
('authorizations.read', '{"fr": "Lire les autorisations", "en": "Read authorizations"}'::jsonb, 'authorizations', '{"fr": "Permet de lire les associations rôle-permission-menu", "en": "Allows reading role-permission-menu associations"}'::jsonb),
('authorizations.update', '{"fr": "Mettre à jour les autorisations", "en": "Update authorizations"}'::jsonb, 'authorizations', '{"fr": "Permet de modifier les associations rôle-permission-menu existantes", "en": "Allows modifying existing role-permission-menu associations"}'::jsonb),
('authorizations.verify', '{"fr": "Vérifier les autorisations (routes)", "en": "Verify authorizations (routes)"}'::jsonb, 'authorizations', '{"fr": "Permet d''utiliser les routes de vérification des permissions", "en": "Allows using permission verification routes"}'::jsonb),
('commissions.read', '{"fr": "Lire commissions", "en": "Read commissions"}'::jsonb, 'payments', '{"fr": "Voir les détails des commissions", "en": "Read commission details"}'::jsonb),
('developer.docs.read', '{"fr": "Documentation développeur", "en": "Developer documentation"}'::jsonb, 'developer', '{"fr": "Accéder à la documentation développeur", "en": "Access developer documentation"}'::jsonb),
('events.archive', '{"fr": "Archiver événement", "en": "Archive event"}'::jsonb, 'events', '{"fr": "Archiver un événement", "en": "Archive an event"}'::jsonb),
('events.create', '{"fr": "Créer événement", "en": "Create event"}'::jsonb, 'events', '{"fr": "Créer de nouveaux événements", "en": "Create new events"}'::jsonb),
('events.delete', '{"fr": "Supprimer événement", "en": "Delete event"}'::jsonb, 'events', '{"fr": "Supprimer des événements", "en": "Delete events"}'::jsonb),
('events.invitations.delete', '{"en":"events.invitations.delete","fr":"events.invitations.delete"}'::jsonb, 'events', NULL),
('events.invitations.read', '{"en":"events.invitations.read","fr":"events.invitations.read"}'::jsonb, 'events', NULL),
('events.invitations.send', '{"en":"events.invitations.send","fr":"events.invitations.send"}'::jsonb, 'events', NULL),
('events.list', '{"fr": "Lister événements", "en": "List events"}'::jsonb, 'events', '{"fr": "Lister tous les événements", "en": "List all events"}'::jsonb),
('events.manage', '{"fr": "Gérer événements", "en": "Manage events"}'::jsonb, 'events', '{"fr": "Gérer tous les aspects des événements", "en": "Manage all event aspects"}'::jsonb),
('events.organizer.analytics', '{"fr": "Analytics événements organizer", "en": "Organizer event analytics"}'::jsonb, 'events', '{"fr": "Voir les statistiques des événements", "en": "View event statistics"}'::jsonb),
('events.organizer.create', '{"fr": "Créer événement organizer", "en": "Create organizer event"}'::jsonb, 'events', '{"fr": "Créer et gérer des événements complets", "en": "Create and manage complete events"}'::jsonb),
('events.organizer.manage', '{"fr": "Gérer événement organizer", "en": "Manage organizer event"}'::jsonb, 'events', '{"fr": "Gestion complète des événements", "en": "Complete event management"}'::jsonb),
('events.organizer.publish', '{"fr": "Publier événement organizer", "en": "Publish organizer event"}'::jsonb, 'events', '{"fr": "Publier des événements", "en": "Publish events"}'::jsonb),
('events.publish', '{"fr": "Publier événement", "en": "Publish event"}'::jsonb, 'events', '{"fr": "Publier un événement", "en": "Publish an event"}'::jsonb),
('events.read', '{"fr": "Voir événement", "en": "Read event"}'::jsonb, 'events', '{"fr": "Voir les détails des événements", "en": "Read event details"}'::jsonb),
('events.restore', '{"fr": "Restaurer événement", "en": "Restore event"}'::jsonb, 'events', '{"fr": "Restaurer un événement", "en": "Restore an event"}'::jsonb),
('events.stats.read', '{"fr": "Statistiques événements", "en": "Event statistics"}'::jsonb, 'events', '{"fr": "Voir les statistiques des événements", "en": "View event statistics"}'::jsonb),
('events.unpublish', '{"fr": "Dépublier événement", "en": "Unpublish event"}'::jsonb, 'events', '{"fr": "Dépublier un événement", "en": "Unpublish an event"}'::jsonb),
('events.update', '{"fr": "Modifier événement", "en": "Update event"}'::jsonb, 'events', '{"fr": "Modifier les informations des événements", "en": "Update event information"}'::jsonb),
('guests.checkin', '{"en":"guests.checkin","fr":"guests.checkin"}'::jsonb, 'guests', NULL),
('guests.create', '{"fr": "Créer invité", "en": "Create guest"}'::jsonb, 'guests', '{"fr": "Créer un nouvel invité", "en": "Create a new guest"}'::jsonb),
('guests.delete', '{"fr": "Supprimer invité", "en": "Delete guest"}'::jsonb, 'guests', '{"fr": "Supprimer un invité", "en": "Delete a guest"}'::jsonb),
('guests.export', '{"fr": "Exporter invités", "en": "Export guests"}'::jsonb, 'guests', '{"fr": "Exporter des invités", "en": "Export guests"}'::jsonb),
('guests.import', '{"fr": "Importer invités", "en": "Import guests"}'::jsonb, 'guests', '{"fr": "Importer des invités", "en": "Import guests"}'::jsonb),
('guests.manage', '{"en":"guests.manage","fr":"guests.manage"}'::jsonb, 'guests', NULL),
('guests.organizer.export', '{"fr": "Exporter invités organizer", "en": "Export organizer guests"}'::jsonb, 'guests', '{"fr": "Exporter des listes d''invités", "en": "Export guest lists"}'::jsonb),
('guests.organizer.import', '{"fr": "Importer invités organizer", "en": "Import organizer guests"}'::jsonb, 'guests', '{"fr": "Importer des listes d''invités", "en": "Import guest lists"}'::jsonb),
('guests.organizer.manage', '{"fr": "Gérer invités organizer", "en": "Manage organizer guests"}'::jsonb, 'guests', '{"fr": "Gestion complète des invités", "en": "Complete guest management"}'::jsonb),
('guests.read', '{"fr": "Voir invité", "en": "Read guest"}'::jsonb, 'guests', '{"fr": "Voir les détails des invités", "en": "Read guest details"}'::jsonb),
('guests.stats.read', '{"en":"guests.stats.read","fr":"guests.stats.read"}'::jsonb, 'guests', NULL),
('guests.update', '{"fr": "Modifier invité", "en": "Update guest"}'::jsonb, 'guests', '{"fr": "Modifier les informations d''un invité", "en": "Update guest information"}'::jsonb),
('invoices.create', '{"fr": "Créer facture", "en": "Create invoice"}'::jsonb, 'payments', '{"fr": "Générer des factures", "en": "Generate invoices"}'::jsonb),
('invoices.read', '{"fr": "Lire facture", "en": "Read invoice"}'::jsonb, 'payments', '{"fr": "Voir les factures", "en": "Read invoices"}'::jsonb),
('manage_events', '{"en":"manage_events","fr":"manage_events"}'::jsonb, 'events', NULL),
('marketplace.admin.read', '{"en":"marketplace.admin.read","fr":"marketplace.admin.read"}'::jsonb, 'marketplace', NULL),
('marketplace.admin.verify', '{"en":"marketplace.admin.verify","fr":"marketplace.admin.verify"}'::jsonb, 'marketplace', NULL),
('marketplace.create', '{"en":"marketplace.create","fr":"marketplace.create"}'::jsonb, 'marketplace', NULL),
('marketplace.design', '{"en":"marketplace.design","fr":"marketplace.design"}'::jsonb, 'marketplace', NULL),
('marketplace.designer.read', '{"fr": "Lire marketplace designer", "en": "Read designer marketplace"}'::jsonb, 'marketplace', '{"fr": "Accès à la marketplace pour designers", "en": "Access designer marketplace"}'::jsonb),
('marketplace.designer.upload', '{"fr": "Uploader sur marketplace", "en": "Upload to marketplace"}'::jsonb, 'marketplace', '{"fr": "Uploader des templates sur la marketplace", "en": "Upload templates to marketplace"}'::jsonb),
('marketplace.designers.create', '{"en":"marketplace.designers.create","fr":"marketplace.designers.create"}'::jsonb, 'marketplace', NULL),
('marketplace.designers.read', '{"en":"marketplace.designers.read","fr":"marketplace.designers.read"}'::jsonb, 'marketplace', NULL),
('marketplace.designers.update', '{"en":"marketplace.designers.update","fr":"marketplace.designers.update"}'::jsonb, 'marketplace', NULL),
('marketplace.moderate', '{"fr": "Modérer marketplace", "en": "Moderate marketplace"}'::jsonb, 'marketplace', '{"fr": "Modérer les templates et designers", "en": "Moderate templates and designers"}'::jsonb),
('marketplace.organizer.purchase', '{"fr": "Acheter marketplace organizer", "en": "Purchase organizer marketplace"}'::jsonb, 'marketplace', '{"fr": "Acheter des templates pour événements", "en": "Purchase templates for events"}'::jsonb),
('marketplace.organizer.read', '{"fr": "Lire marketplace organizer", "en": "Read organizer marketplace"}'::jsonb, 'marketplace', '{"fr": "Accès à la marketplace pour achats", "en": "Access marketplace for purchases"}'::jsonb),
('marketplace.purchase', '{"fr": "Acheter marketplace", "en": "Purchase marketplace"}'::jsonb, 'marketplace', '{"fr": "Acheter sur le marketplace", "en": "Purchase on marketplace"}'::jsonb),
('marketplace.purchases.read', '{"en":"marketplace.purchases.read","fr":"marketplace.purchases.read"}'::jsonb, 'marketplace', NULL),
('marketplace.read', '{"fr": "Lire marketplace", "en": "Read marketplace"}'::jsonb, 'marketplace', '{"fr": "Lire le contenu du marketplace", "en": "Read marketplace content"}'::jsonb),
('marketplace.reviews.create', '{"en":"marketplace.reviews.create","fr":"marketplace.reviews.create"}'::jsonb, 'marketplace', NULL),
('marketplace.reviews.read', '{"en":"marketplace.reviews.read","fr":"marketplace.reviews.read"}'::jsonb, 'marketplace', NULL),
('marketplace.stats.read', '{"en":"marketplace.stats.read","fr":"marketplace.stats.read"}'::jsonb, 'marketplace', NULL),
('marketplace.templates.approve', '{"en":"marketplace.templates.approve","fr":"marketplace.templates.approve"}'::jsonb, 'marketplace', NULL),
('marketplace.templates.create', '{"en":"marketplace.templates.create","fr":"marketplace.templates.create"}'::jsonb, 'marketplace', NULL),
('marketplace.templates.delete', '{"en":"marketplace.templates.delete","fr":"marketplace.templates.delete"}'::jsonb, 'marketplace', NULL),
('marketplace.templates.purchase', '{"en":"marketplace.templates.purchase","fr":"marketplace.templates.purchase"}'::jsonb, 'marketplace', NULL),
('marketplace.templates.read', '{"en":"marketplace.templates.read","fr":"marketplace.templates.read"}'::jsonb, 'marketplace', NULL),
('marketplace.templates.reject', '{"en":"marketplace.templates.reject","fr":"marketplace.templates.reject"}'::jsonb, 'marketplace', NULL),
('marketplace.templates.update', '{"en":"marketplace.templates.update","fr":"marketplace.templates.update"}'::jsonb, 'marketplace', NULL),
('marketplace.update', '{"en":"marketplace.update","fr":"marketplace.update"}'::jsonb, 'marketplace', NULL),
('menus.assign_permissions', '{"fr": "Assigner permissions menu", "en": "Assign menu permissions"}'::jsonb, 'menus', '{"fr": "Assigner des permissions aux menus", "en": "Assign permissions to menus"}'::jsonb),
('menus.create', '{"fr": "Créer menu", "en": "Create menu"}'::jsonb, 'menus', '{"fr": "Créer de nouveaux menus", "en": "Create new menus"}'::jsonb),
('menus.delete', '{"fr": "Supprimer menu", "en": "Delete menu"}'::jsonb, 'menus', '{"fr": "Supprimer des menus", "en": "Delete menus"}'::jsonb),
('menus.list', '{"fr": "Lister menus", "en": "List menus"}'::jsonb, 'menus', '{"fr": "Lister tous les menus", "en": "List all menus"}'::jsonb),
('menus.manage', '{"en":"menus.manage","fr":"menus.manage"}'::jsonb, 'menus', NULL),
('menus.read', '{"fr": "Voir menu", "en": "Read menu"}'::jsonb, 'menus', '{"fr": "Voir les détails des menus", "en": "Read menu details"}'::jsonb),
('menus.update', '{"fr": "Modifier menu", "en": "Update menu"}'::jsonb, 'menus', '{"fr": "Modifier les informations des menus", "en": "Update menu information"}'::jsonb),
('menus.view_stats', '{"fr": "Statistiques menus", "en": "Menus Statistics"}'::jsonb, 'menus', '{"fr": "Voir les statistiques des menus", "en": "View menus statistics"}'::jsonb),
('notifications.admin', '{"fr": "Admin notifications", "en": "Notifications admin"}'::jsonb, 'notifications', '{"fr": "Administration du service de notifications", "en": "Notifications service administration"}'::jsonb),
('notifications.bulk.mixed', '{"fr": "Notifications mixtes", "en": "Mixed notifications"}'::jsonb, 'notifications', '{"fr": "Envoyer des notifications mixtes en lot", "en": "Send mixed bulk notifications"}'::jsonb),
('notifications.designer.send', '{"fr": "Notifications designer", "en": "Designer notifications"}'::jsonb, 'notifications', '{"fr": "Envoyer des notifications liées aux templates", "en": "Send template-related notifications"}'::jsonb),
('notifications.email.bulk', '{"fr": "Emails en lot", "en": "Bulk emails"}'::jsonb, 'notifications', '{"fr": "Envoyer des emails en lot", "en": "Send bulk emails"}'::jsonb),
('notifications.email.queue', '{"fr": "Mettre email en file", "en": "Queue email"}'::jsonb, 'notifications', '{"fr": "Mettre des emails en file d''attente", "en": "Queue emails"}'::jsonb),
('notifications.email.send', '{"fr": "Envoyer email", "en": "Send email"}'::jsonb, 'notifications', '{"fr": "Envoyer des emails", "en": "Send emails"}'::jsonb),
('notifications.event-confirmation.send', '{"fr": "Envoyer confirmation événement", "en": "Send event confirmation"}'::jsonb, 'notifications', '{"fr": "Envoyer des confirmations d''événement", "en": "Send event confirmations"}'::jsonb),
('notifications.jobs.cancel', '{"fr": "Annuler job notification", "en": "Cancel notification job"}'::jsonb, 'notifications', '{"fr": "Annuler un job de notification", "en": "Cancel a notification job"}'::jsonb),
('notifications.jobs.read', '{"fr": "Lire jobs notifications", "en": "Read notification jobs"}'::jsonb, 'notifications', '{"fr": "Voir les jobs de notifications", "en": "View notification jobs"}'::jsonb),
('notifications.organizer.send', '{"fr": "Notifications organizer", "en": "Organizer notifications"}'::jsonb, 'notifications', '{"fr": "Envoyer des notifications événementielles", "en": "Send event notifications"}'::jsonb),
('notifications.otp.send', '{"fr": "Envoyer OTP", "en": "Send OTP"}'::jsonb, 'notifications', '{"fr": "Envoyer des codes OTP", "en": "Send OTP codes"}'::jsonb),
('notifications.password-reset.send', '{"fr": "Envoyer réinitialisation mot de passe", "en": "Send password reset"}'::jsonb, 'notifications', '{"fr": "Envoyer des emails/SMS de réinitialisation de mot de passe", "en": "Send password reset emails/SMS"}'::jsonb),
('notifications.send', '{"en":"notifications.send","fr":"notifications.send"}'::jsonb, 'notifications', NULL),
('notifications.sms.bulk', '{"fr": "SMS en lot", "en": "Bulk SMS"}'::jsonb, 'notifications', '{"fr": "Envoyer des SMS en lot", "en": "Send bulk SMS"}'::jsonb),
('notifications.sms.queue', '{"fr": "Mettre SMS en file", "en": "Queue SMS"}'::jsonb, 'notifications', '{"fr": "Mettre des SMS en file d''attente", "en": "Queue SMS"}'::jsonb),
('notifications.sms.send', '{"fr": "Envoyer SMS", "en": "Send SMS"}'::jsonb, 'notifications', '{"fr": "Envoyer des SMS", "en": "Send SMS"}'::jsonb),
('notifications.stats.read', '{"fr": "Statistiques notifications", "en": "Notification statistics"}'::jsonb, 'notifications', '{"fr": "Voir les statistiques des notifications", "en": "View notification statistics"}'::jsonb),
('notifications.welcome.send', '{"fr": "Envoyer bienvenue", "en": "Send welcome"}'::jsonb, 'notifications', '{"fr": "Envoyer des messages de bienvenue", "en": "Send welcome messages"}'::jsonb),
('otp.manage', '{"fr": "Gérer OTP", "en": "Manage OTP"}'::jsonb, 'otp', '{"fr": "Gérer les OTP (créer, modifier, supprimer)", "en": "Manage OTP (create, update, delete)"}'::jsonb),
('otp.read', '{"fr": "Voir OTP", "en": "Read OTP"}'::jsonb, 'otp', '{"fr": "Voir les détails des OTP", "en": "Read OTP details"}'::jsonb),
('otp.stats', '{"fr": "Statistiques OTP", "en": "OTP Statistics"}'::jsonb, 'otp', '{"fr": "Voir les statistiques des OTP", "en": "View OTP statistics"}'::jsonb),
('payment-methods.create', '{"fr": "Créer méthode paiement", "en": "Create payment method"}'::jsonb, 'payments', '{"fr": "Créer des méthodes de paiement", "en": "Create payment methods"}'::jsonb),
('payment-methods.delete', '{"fr": "Supprimer méthode paiement", "en": "Delete payment method"}'::jsonb, 'payments', '{"fr": "Supprimer des méthodes de paiement", "en": "Delete payment methods"}'::jsonb),
('payment-methods.read', '{"fr": "Lire méthodes paiement", "en": "Read payment methods"}'::jsonb, 'payments', '{"fr": "Voir les méthodes de paiement", "en": "Read payment methods"}'::jsonb),
('payment-methods.update', '{"fr": "Modifier méthode paiement", "en": "Update payment method"}'::jsonb, 'payments', '{"fr": "Modifier les méthodes de paiement", "en": "Update payment methods"}'::jsonb),
('payments.cancel', '{"fr": "Annuler paiement", "en": "Cancel payment"}'::jsonb, 'payments', '{"fr": "Annuler des paiements", "en": "Cancel payments"}'::jsonb),
('payments.create', '{"fr": "Créer paiement", "en": "Create payment"}'::jsonb, 'payments', '{"fr": "Créer des paiements", "en": "Create payments"}'::jsonb),
('payments.customers.create', '{"fr": "Créer client", "en": "Create customer"}'::jsonb, 'payments', '{"fr": "Créer de nouveaux clients", "en": "Create new customers"}'::jsonb),
('payments.customers.read', '{"fr": "Lire clients", "en": "Read customers"}'::jsonb, 'payments', '{"fr": "Voir les informations des clients", "en": "Read customer information"}'::jsonb),
('payments.invoices.create', '{"fr": "Créer facture", "en": "Create invoice"}'::jsonb, 'payments', '{"fr": "Générer des factures", "en": "Generate invoices"}'::jsonb),
('payments.invoices.read', '{"fr": "Lire factures", "en": "Read invoices"}'::jsonb, 'payments', '{"fr": "Voir les factures", "en": "Read invoices"}'::jsonb),
('payments.organizer.read', '{"fr": "Lire paiements organizer", "en": "Read organizer payments"}'::jsonb, 'payments', '{"fr": "Voir les paiements d''événements", "en": "View event payments"}'::jsonb),
('payments.organizer.refunds', '{"fr": "Remboursements organizer", "en": "Organizer refunds"}'::jsonb, 'payments', '{"fr": "Gérer les remboursements d''événements", "en": "Manage event refunds"}'::jsonb),
('payments.payment-methods.create', '{"fr": "Créer méthode paiement", "en": "Create payment method"}'::jsonb, 'payments', '{"fr": "Créer des méthodes de paiement", "en": "Create payment methods"}'::jsonb),
('payments.payment-methods.read', '{"fr": "Lire méthodes paiement", "en": "Read payment methods"}'::jsonb, 'payments', '{"fr": "Voir les méthodes de paiement", "en": "Read payment methods"}'::jsonb),
('payments.paypal.capture', '{"fr": "Capturer paiement PayPal", "en": "Capture PayPal payment"}'::jsonb, 'payments', '{"fr": "Capturer des paiements PayPal", "en": "Capture PayPal payments"}'::jsonb),
('payments.paypal.create', '{"fr": "Créer paiement PayPal", "en": "Create PayPal payment"}'::jsonb, 'payments', '{"fr": "Créer des paiements PayPal", "en": "Create PayPal payments"}'::jsonb),
('payments.process', '{"en":"payments.process","fr":"payments.process"}'::jsonb, 'payments', NULL),
('payments.read', '{"fr": "Lire paiements", "en": "Read payments"}'::jsonb, 'payments', '{"fr": "Voir les détails des paiements", "en": "Read payment details"}'::jsonb),
('payments.refunds.create', '{"fr": "Créer remboursement", "en": "Create refund"}'::jsonb, 'payments', '{"fr": "Créer des remboursements", "en": "Create refunds"}'::jsonb),
('payments.refunds.read', '{"fr": "Lire remboursements", "en": "Read refunds"}'::jsonb, 'payments', '{"fr": "Voir les détails des remboursements", "en": "Read refund details"}'::jsonb),
('payments.stats.read', '{"fr": "Statistiques paiements", "en": "Payment statistics"}'::jsonb, 'payments', '{"fr": "Voir les statistiques des paiements", "en": "View payment statistics"}'::jsonb),
('payments.stripe.create', '{"fr": "Créer paiement Stripe", "en": "Create Stripe payment"}'::jsonb, 'payments', '{"fr": "Créer des paiements Stripe", "en": "Create Stripe payments"}'::jsonb),
('payments.update', '{"fr": "Modifier paiement", "en": "Update payment"}'::jsonb, 'payments', '{"fr": "Modifier les informations des paiements", "en": "Update payment information"}'::jsonb),
('people.create', '{"fr": "Créer personne", "en": "Create person"}'::jsonb, 'people', '{"fr": "Créer de nouvelles personnes", "en": "Create new people"}'::jsonb),
('people.delete', '{"fr": "Supprimer personne", "en": "Delete person"}'::jsonb, 'people', '{"fr": "Supprimer des personnes", "en": "Delete people"}'::jsonb),
('people.list', '{"fr": "Lister personnes", "en": "List people"}'::jsonb, 'people', '{"fr": "Lister toutes les personnes", "en": "List all people"}'::jsonb),
('people.read', '{"fr": "Voir personne", "en": "Read person"}'::jsonb, 'people', '{"fr": "Voir les détails des personnes", "en": "Read person details"}'::jsonb),
('people.stats', '{"fr": "Statistiques personnes", "en": "People Statistics"}'::jsonb, 'people', '{"fr": "Voir les statistiques des personnes", "en": "View people statistics"}'::jsonb),
('people.update', '{"fr": "Modifier personne", "en": "Update person"}'::jsonb, 'people', '{"fr": "Modifier les informations des personnes", "en": "Update person information"}'::jsonb),
('permissions.create', '{"fr": "Créer permission", "en": "Create permission"}'::jsonb, 'permissions', '{"fr": "Créer de nouvelles permissions", "en": "Create new permissions"}'::jsonb),
('permissions.delete', '{"fr": "Supprimer permission", "en": "Delete permission"}'::jsonb, 'permissions', '{"fr": "Supprimer des permissions", "en": "Delete permissions"}'::jsonb),
('permissions.list', '{"fr": "Lister permissions", "en": "List permissions"}'::jsonb, 'permissions', '{"fr": "Lister toutes les permissions", "en": "List all permissions"}'::jsonb),
('permissions.manage', '{"en":"permissions.manage","fr":"permissions.manage"}'::jsonb, 'permissions', NULL),
('permissions.read', '{"fr": "Voir permission", "en": "Read permission"}'::jsonb, 'permissions', '{"fr": "Voir les détails des permissions", "en": "Read permission details"}'::jsonb),
('permissions.update', '{"fr": "Modifier permission", "en": "Update permission"}'::jsonb, 'permissions', '{"fr": "Modifier les informations des permissions", "en": "Update permission information"}'::jsonb),
('permissions.verify', '{"en":"permissions.verify","fr":"permissions.verify"}'::jsonb, 'permissions', NULL),
('permissions.view_stats', '{"fr": "Statistiques permissions", "en": "Permissions Statistics"}'::jsonb, 'permissions', '{"fr": "Voir les statistiques des permissions", "en": "View permissions statistics"}'::jsonb),
('refunds.create', '{"fr": "Créer remboursement", "en": "Create refund"}'::jsonb, 'payments', '{"fr": "Créer des remboursements", "en": "Create refunds"}'::jsonb),
('refunds.read', '{"fr": "Lire remboursement", "en": "Read refund"}'::jsonb, 'payments', '{"fr": "Voir les détails des remboursements", "en": "Read refund details"}'::jsonb),
('roles.assign', '{"fr": "Assigner rôle", "en": "Assign role"}'::jsonb, 'roles', '{"fr": "Assigner des rôles aux utilisateurs", "en": "Assign roles to users"}'::jsonb),
('roles.assign_permissions', '{"fr": "Assigner permissions rôle", "en": "Assign role permissions"}'::jsonb, 'roles', '{"fr": "Assigner des permissions aux rôles", "en": "Assign permissions to roles"}'::jsonb),
('roles.create', '{"fr": "Créer rôle", "en": "Create role"}'::jsonb, 'roles', '{"fr": "Créer de nouveaux rôles", "en": "Create new roles"}'::jsonb),
('roles.delete', '{"fr": "Supprimer rôle", "en": "Delete role"}'::jsonb, 'roles', '{"fr": "Supprimer des rôles", "en": "Delete roles"}'::jsonb),
('roles.list', '{"fr": "Lister rôles", "en": "List roles"}'::jsonb, 'roles', '{"fr": "Lister tous les rôles", "en": "List all roles"}'::jsonb),
('roles.manage', '{"en":"roles.manage","fr":"roles.manage"}'::jsonb, 'roles', NULL),
('roles.read', '{"fr": "Voir rôle", "en": "Read role"}'::jsonb, 'roles', '{"fr": "Voir les détails des rôles", "en": "Read role details"}'::jsonb),
('roles.update', '{"fr": "Modifier rôle", "en": "Update role"}'::jsonb, 'roles', '{"fr": "Modifier les informations des rôles", "en": "Update role information"}'::jsonb),
('roles.verify', '{"en":"roles.verify","fr":"roles.verify"}'::jsonb, 'roles', NULL),
('roles.view_stats', '{"fr": "Statistiques rôles", "en": "Roles Statistics"}'::jsonb, 'roles', '{"fr": "Voir les statistiques des rôles", "en": "View roles statistics"}'::jsonb),
('scans.devices.create', '{"fr": "Créer appareil scan", "en": "Create scan device"}'::jsonb, 'scans', '{"fr": "Créer des appareils de scan", "en": "Create scan devices"}'::jsonb),
('scans.devices.read', '{"fr": "Lire appareil scan", "en": "Read scan device"}'::jsonb, 'scans', '{"fr": "Voir les détails des appareils de scan", "en": "Read scan device details"}'::jsonb),
('scans.fraud.analyze', '{"fr": "Analyser fraude scan", "en": "Analyze scan fraud"}'::jsonb, 'scans', '{"fr": "Analyser les activités frauduleuses de scan", "en": "Analyze fraudulent scan activities"}'::jsonb),
('scans.fraud.read', '{"fr": "Lire fraude scan", "en": "Read scan fraud"}'::jsonb, 'scans', '{"fr": "Voir les rapports de fraude de scan", "en": "Read scan fraud reports"}'::jsonb),
('scans.history.read', '{"fr": "Lire historique scans", "en": "Read scan history"}'::jsonb, 'scans', '{"fr": "Voir l''historique des scans", "en": "View scan history"}'::jsonb),
('scans.offline.cleanup', '{"fr": "Nettoyer offline", "en": "Cleanup offline"}'::jsonb, 'scans', '{"fr": "Nettoyer les données offline expirées", "en": "Cleanup expired offline data"}'::jsonb),
('scans.offline.read', '{"fr": "Lire données offline", "en": "Read offline data"}'::jsonb, 'scans', '{"fr": "Voir les données offline", "en": "Read offline data"}'::jsonb),
('scans.offline.sync', '{"fr": "Synchroniser offline", "en": "Sync offline"}'::jsonb, 'scans', '{"fr": "Synchroniser les données offline", "en": "Sync offline data"}'::jsonb),
('scans.operators.create', '{"fr": "Créer opérateur scan", "en": "Create scan operator"}'::jsonb, 'scans', '{"fr": "Créer des opérateurs de scan", "en": "Create scan operators"}'::jsonb),
('scans.operators.read', '{"fr": "Lire opérateur scan", "en": "Read scan operator"}'::jsonb, 'scans', '{"fr": "Voir les détails des opérateurs de scan", "en": "Read scan operator details"}'::jsonb),
('scans.qr.batch', '{"fr": "QR codes en lot", "en": "Batch QR codes"}'::jsonb, 'scans', '{"fr": "Générer des QR codes en lot", "en": "Generate batch QR codes"}'::jsonb),
('scans.qr.decode', '{"fr": "Décoder QR code", "en": "Decode QR code"}'::jsonb, 'scans', '{"fr": "Décoder et valider des QR codes", "en": "Decode and validate QR codes"}'::jsonb),
('scans.qr.generate', '{"fr": "Générer QR code", "en": "Generate QR code"}'::jsonb, 'scans', '{"fr": "Générer des QR codes", "en": "Generate QR codes"}'::jsonb),
('scans.qr.test', '{"fr": "Tester QR code", "en": "Test QR code"}'::jsonb, 'scans', '{"fr": "Générer des QR codes de test", "en": "Generate test QR codes"}'::jsonb),
('scans.reports.generate', '{"fr": "Générer rapport scans", "en": "Generate scan reports"}'::jsonb, 'scans', '{"fr": "Générer des rapports de validation", "en": "Generate validation reports"}'::jsonb),
('scans.sessions.create', '{"fr": "Créer session scan", "en": "Create scan session"}'::jsonb, 'scans', '{"fr": "Créer des sessions de scan", "en": "Create scan sessions"}'::jsonb),
('scans.sessions.read', '{"fr": "Lire session scan", "en": "Read scan session"}'::jsonb, 'scans', '{"fr": "Voir les détails des sessions de scan", "en": "Read scan session details"}'::jsonb),
('scans.sessions.update', '{"fr": "Modifier session scan", "en": "Update scan session"}'::jsonb, 'scans', '{"fr": "Modifier des sessions de scan", "en": "Update scan sessions"}'::jsonb),
('scans.stats.read', '{"fr": "Statistiques scans", "en": "Scan statistics"}'::jsonb, 'scans', '{"fr": "Voir les statistiques des scans", "en": "View scan statistics"}'::jsonb),
('scans.validate', '{"fr": "Valider scan", "en": "Validate scan"}'::jsonb, 'scans', '{"fr": "Valider des scans de tickets", "en": "Validate ticket scans"}'::jsonb),
('scans.validate.offline', '{"fr": "Valider scan offline", "en": "Validate offline scan"}'::jsonb, 'scans', '{"fr": "Valider des scans en mode offline", "en": "Validate scans in offline mode"}'::jsonb),
('sessions.cleanup', '{"fr": "Nettoyer sessions", "en": "Cleanup sessions"}'::jsonb, 'sessions', '{"fr": "Nettoyer les sessions expirées", "en": "Cleanup expired sessions"}'::jsonb),
('sessions.manage', '{"en":"sessions.manage","fr":"sessions.manage"}'::jsonb, 'sessions', NULL),
('sessions.monitor', '{"fr": "Monitorer sessions", "en": "Monitor sessions"}'::jsonb, 'sessions', '{"fr": "Surveiller les sessions actives", "en": "Monitor active sessions"}'::jsonb),
('sessions.read', '{"fr": "Voir sessions", "en": "Read sessions"}'::jsonb, 'sessions', '{"fr": "Voir les détails des sessions", "en": "Read session details"}'::jsonb),
('sessions.revoke', '{"fr": "Révoquer sessions", "en": "Revoke sessions"}'::jsonb, 'sessions', '{"fr": "Révoquer des sessions utilisateur", "en": "Revoke user sessions"}'::jsonb),
('system.admin', '{"fr": "Administration système", "en": "System Administration"}'::jsonb, 'system', '{"fr": "Accès complet à l''administration du système", "en": "Full system administration access"}'::jsonb),
('system.audit', '{"fr": "Audit système", "en": "System audit"}'::jsonb, 'system', '{"fr": "Permet d''accéder aux logs et rapports d''audit", "en": "Allows accessing audit logs and reports"}'::jsonb),
('system.config', '{"fr": "Configuration système", "en": "System Configuration"}'::jsonb, 'system', '{"fr": "Configurer les paramètres système avancés", "en": "Configure advanced system settings"}'::jsonb),
('system.dashboard', '{"fr": "Tableau de bord", "en": "Dashboard"}'::jsonb, 'system', '{"fr": "Accéder au tableau de bord", "en": "Access dashboard"}'::jsonb),
('system.logs', '{"fr": "Voir logs", "en": "View logs"}'::jsonb, 'system', '{"fr": "Voir les logs système", "en": "View system logs"}'::jsonb),
('system.monitor', '{"fr": "Monitoring système", "en": "System Monitoring"}'::jsonb, 'system', '{"fr": "Accéder au monitoring système avancé", "en": "Access advanced system monitoring"}'::jsonb),
('system.monitoring', '{"fr": "Monitoring", "en": "Monitoring"}'::jsonb, 'system', '{"fr": "Accéder au monitoring système", "en": "Access system monitoring"}'::jsonb),
('system.settings', '{"fr": "Paramètres système", "en": "System settings"}'::jsonb, 'system', '{"fr": "Configurer les paramètres système", "en": "Configure system settings"}'::jsonb),
('templates.analytics', '{"fr": "Analytics templates", "en": "Template analytics"}'::jsonb, 'templates', '{"fr": "Voir les statistiques de ventes de templates", "en": "View template sales analytics"}'::jsonb),
('templates.design', '{"fr": "Designer template", "en": "Design template"}'::jsonb, 'templates', '{"fr": "Créer et designer des templates visuels", "en": "Create and design visual templates"}'::jsonb),
('templates.publish', '{"fr": "Publier template", "en": "Publish template"}'::jsonb, 'templates', '{"fr": "Publier des templates sur la marketplace", "en": "Publish templates on marketplace"}'::jsonb),
('templates.sell', '{"fr": "Vendre template", "en": "Sell template"}'::jsonb, 'templates', '{"fr": "Vendre des templates sur la marketplace", "en": "Sell templates on marketplace"}'::jsonb),
('tickets.admin', '{"fr": "Admin tickets", "en": "Tickets admin"}'::jsonb, 'tickets', '{"fr": "Administration du service de génération de tickets", "en": "Ticket generation service administration"}'::jsonb),
('tickets.batch.create', '{"fr": "Créer tickets en lot", "en": "Create batch tickets"}'::jsonb, 'tickets', '{"fr": "Générer des tickets en lot", "en": "Generate batch tickets"}'::jsonb),
('tickets.create', '{"en":"tickets.create","fr":"tickets.create"}'::jsonb, 'tickets', NULL),
('tickets.delete', '{"en":"tickets.delete","fr":"tickets.delete"}'::jsonb, 'tickets', NULL),
('tickets.full.batch', '{"fr": "Batch complet tickets", "en": "Full batch tickets"}'::jsonb, 'tickets', '{"fr": "Générer un traitement batch complet", "en": "Generate full batch processing"}'::jsonb),
('tickets.generate', '{"fr": "Générer ticket", "en": "Generate ticket"}'::jsonb, 'tickets', '{"fr": "Générer un ticket", "en": "Generate a ticket"}'::jsonb),
('tickets.jobs.cancel', '{"fr": "Annuler job ticket", "en": "Cancel ticket job"}'::jsonb, 'tickets', '{"fr": "Annuler un job de génération de tickets", "en": "Cancel a ticket generation job"}'::jsonb),
('tickets.jobs.create', '{"fr": "Créer job ticket", "en": "Create ticket job"}'::jsonb, 'tickets', '{"fr": "Créer des jobs de génération de tickets", "en": "Create ticket generation jobs"}'::jsonb),
('tickets.jobs.process', '{"fr": "Traiter job ticket", "en": "Process ticket job"}'::jsonb, 'tickets', '{"fr": "Traiter des jobs de génération de tickets", "en": "Process ticket generation jobs"}'::jsonb),
('tickets.jobs.read', '{"fr": "Lire jobs tickets", "en": "Read ticket jobs"}'::jsonb, 'tickets', '{"fr": "Voir les jobs de génération de tickets", "en": "Read ticket generation jobs"}'::jsonb),
('tickets.organizer.analytics', '{"fr": "Analytics tickets organizer", "en": "Organizer ticket analytics"}'::jsonb, 'tickets', '{"fr": "Voir les statistiques des tickets", "en": "View ticket statistics"}'::jsonb),
('tickets.organizer.generate', '{"fr": "Générer tickets organizer", "en": "Generate organizer tickets"}'::jsonb, 'tickets', '{"fr": "Générer des tickets pour événements", "en": "Generate event tickets"}'::jsonb),
('tickets.organizer.validate', '{"fr": "Valider tickets organizer", "en": "Validate organizer tickets"}'::jsonb, 'tickets', '{"fr": "Valider des tickets d''événements", "en": "Validate event tickets"}'::jsonb),
('tickets.pdf.batch', '{"fr": "PDF tickets en lot", "en": "Batch ticket PDFs"}'::jsonb, 'tickets', '{"fr": "Générer des PDFs en lot", "en": "Generate batch PDFs"}'::jsonb),
('tickets.pdf.create', '{"fr": "Créer PDF ticket", "en": "Create ticket PDF"}'::jsonb, 'tickets', '{"fr": "Générer des PDF pour les tickets", "en": "Generate PDFs for tickets"}'::jsonb),
('tickets.process', '{"fr": "Traiter ticket", "en": "Process ticket"}'::jsonb, 'tickets', '{"fr": "Traiter un ticket", "en": "Process a ticket"}'::jsonb),
('tickets.read', '{"en":"tickets.read","fr":"tickets.read"}'::jsonb, 'tickets', NULL),
('tickets.stats.read', '{"fr": "Statistiques tickets", "en": "Ticket statistics"}'::jsonb, 'tickets', '{"fr": "Voir les statistiques des tickets", "en": "View ticket statistics"}'::jsonb),
('tickets.templates.create', '{"en":"tickets.templates.create","fr":"tickets.templates.create"}'::jsonb, 'tickets', NULL),
('tickets.templates.delete', '{"en":"tickets.templates.delete","fr":"tickets.templates.delete"}'::jsonb, 'tickets', NULL),
('tickets.templates.read', '{"en":"tickets.templates.read","fr":"tickets.templates.read"}'::jsonb, 'tickets', NULL),
('tickets.templates.update', '{"en":"tickets.templates.update","fr":"tickets.templates.update"}'::jsonb, 'tickets', NULL),
('tickets.templates.validate', '{"en":"tickets.templates.validate","fr":"tickets.templates.validate"}'::jsonb, 'tickets', NULL),
('tickets.types.create', '{"en":"tickets.types.create","fr":"tickets.types.create"}'::jsonb, 'tickets', NULL),
('tickets.types.delete', '{"en":"tickets.types.delete","fr":"tickets.types.delete"}'::jsonb, 'tickets', NULL),
('tickets.types.read', '{"en":"tickets.types.read","fr":"tickets.types.read"}'::jsonb, 'tickets', NULL),
('tickets.types.update', '{"en":"tickets.types.update","fr":"tickets.types.update"}'::jsonb, 'tickets', NULL),
('tickets.update', '{"en":"tickets.update","fr":"tickets.update"}'::jsonb, 'tickets', NULL),
('tickets.validate', '{"fr": "Valider ticket", "en": "Validate ticket"}'::jsonb, 'tickets', '{"fr": "Valider un ticket", "en": "Validate a ticket"}'::jsonb),
('users.create', '{"fr": "Créer utilisateur", "en": "Create user"}'::jsonb, 'users', '{"fr": "Créer de nouveaux utilisateurs", "en": "Create new users"}'::jsonb),
('users.delete', '{"fr": "Supprimer utilisateur", "en": "Delete user"}'::jsonb, 'users', '{"fr": "Supprimer des utilisateurs", "en": "Delete users"}'::jsonb),
('users.list', '{"fr": "Lister utilisateurs", "en": "List users"}'::jsonb, 'users', '{"fr": "Lister tous les utilisateurs", "en": "List all users"}'::jsonb),
('users.read', '{"fr": "Voir utilisateur", "en": "Read user"}'::jsonb, 'users', '{"fr": "Voir les détails des utilisateurs", "en": "Read user details"}'::jsonb),
('users.stats', '{"fr": "Statistiques utilisateurs", "en": "Users Statistics"}'::jsonb, 'users', '{"fr": "Voir les statistiques des utilisateurs", "en": "View users statistics"}'::jsonb),
('users.update', '{"fr": "Modifier utilisateur", "en": "Update user"}'::jsonb, 'users', '{"fr": "Modifier les informations utilisateur", "en": "Update user information"}'::jsonb),
('wallets.read', '{"fr": "Lire portefeuille", "en": "Read wallet"}'::jsonb, 'payments', '{"fr": "Voir les informations des portefeuilles", "en": "Read wallet information"}'::jsonb),
('wallets.withdraw', '{"fr": "Retirer portefeuille", "en": "Withdraw wallet"}'::jsonb, 'payments', '{"fr": "Effectuer des retraits des portefeuilles", "en": "Withdraw from wallets"}'::jsonb)
ON CONFLICT (code) DO NOTHING;

-- Nettoyage des autorisations liées à des permissions supprimées
DELETE FROM authorizations
WHERE permission_id IN (
  SELECT id FROM permissions WHERE code NOT IN (SELECT code FROM desired_permissions)
);

-- Suppression des permissions obsolètes
DELETE FROM permissions
WHERE code NOT IN (SELECT code FROM desired_permissions);

-- Insertion / mise à jour des permissions normalisées
INSERT INTO permissions (code, label, "group", description, created_at, updated_at)
SELECT code, label, "group", description, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM desired_permissions
ON CONFLICT (code) DO UPDATE SET
  label = EXCLUDED.label,
  "group" = EXCLUDED."group",
  description = EXCLUDED.description,
  deleted_at = NULL,
  updated_at = CURRENT_TIMESTAMP;

DROP TABLE desired_permissions;

DO $$
BEGIN
  RAISE NOTICE '✅ Permissions normalisées: % permissions actives', (SELECT COUNT(*) FROM permissions WHERE deleted_at IS NULL);
END $$;
