-- ========================================
-- SEED PERMISSIONS (reconciled)
-- ========================================

DELETE FROM permissions WHERE code IS NOT NULL;

INSERT INTO permissions (code, label, "group", description, created_at, updated_at) VALUES
('accesses.assign', '{"fr":"Assigner accès","en":"Assign access"}'::jsonb, 'accesses', NULL, NOW(), NOW()),
('accesses.create', '{"fr":"Créer accès","en":"Create access"}'::jsonb, 'accesses', NULL, NOW(), NOW()),
('accesses.delete', '{"fr":"Supprimer accès","en":"Delete access"}'::jsonb, 'accesses', NULL, NOW(), NOW()),
('accesses.hard_delete', '{"fr":"Hard delete access" , "en":"Hard delete access"}'::jsonb, 'accesses', NULL, NOW(), NOW()),
('accesses.read', '{"fr":"Lire accès","en":"Read access"}'::jsonb, 'accesses', NULL, NOW(), NOW()),
('accesses.remove', '{"fr":"Retirer accès","en":"Remove access"}'::jsonb, 'accesses', NULL, NOW(), NOW()),
('accesses.update', '{"fr":"Modifier accès","en":"Update access"}'::jsonb, 'accesses', NULL, NOW(), NOW()),
('admin.dashboard.read', '{"fr":"admin.dashboard.read","en":"admin.dashboard.read"}'::jsonb, 'admin', NULL, NOW(), NOW()),
('admin.health.read', '{"fr":"admin.health.read","en":"admin.health.read"}'::jsonb, 'admin', NULL, NOW(), NOW()),
('admin.metrics.read', '{"fr":"admin.metrics.read","en":"admin.metrics.read"}'::jsonb, 'admin', NULL, NOW(), NOW()),
('admin.metrics.reset', '{"fr":"admin.metrics.reset","en":"admin.metrics.reset"}'::jsonb, 'admin', NULL, NOW(), NOW()),
('admin.security.read', '{"fr":"admin.security.read","en":"admin.security.read"}'::jsonb, 'admin', NULL, NOW(), NOW()),
('authorizations.create', '{"fr":"Créer authorization","en":"Create authorization"}'::jsonb, 'authorizations', NULL, NOW(), NOW()),
('authorizations.delete', '{"fr":"Supprimer authorization","en":"Delete authorization"}'::jsonb, 'authorizations', NULL, NOW(), NOW()),
('authorizations.hard_delete', '{"fr":"Hard delete authorization","en":"Hard delete authorization"}'::jsonb, 'authorizations', NULL, NOW(), NOW()),
('authorizations.manage', '{"fr":"Manage authorization","en":"Manage authorization"}'::jsonb, 'authorizations', NULL, NOW(), NOW()),
('authorizations.read', '{"fr":"Lire authorization","en":"Read authorization"}'::jsonb, 'authorizations', NULL, NOW(), NOW()),
('authorizations.update', '{"fr":"Modifier authorization","en":"Update authorization"}'::jsonb, 'authorizations', NULL, NOW(), NOW()),
('authorizations.verify', '{"fr":"Vérifier authorization","en":"Verify authorization"}'::jsonb, 'authorizations', NULL, NOW(), NOW()),
('developer.docs.read', '{"fr":"developer.docs.read","en":"developer.docs.read"}'::jsonb, 'developer', NULL, NOW(), NOW()),
('events.archive', '{"fr":"Archiver événement","en":"Archive event"}'::jsonb, 'events', NULL, NOW(), NOW()),
('events.create', '{"fr":"Créer événement","en":"Create event"}'::jsonb, 'events', NULL, NOW(), NOW()),
('events.delete', '{"fr":"Supprimer événement","en":"Delete event"}'::jsonb, 'events', NULL, NOW(), NOW()),
('events.invitations.delete', '{"fr":"Supprimer invitations","en":"Delete invitations"}'::jsonb, 'events', NULL, NOW(), NOW()),
('events.invitations.read', '{"fr":"Lire invitations","en":"Read invitations"}'::jsonb, 'events', NULL, NOW(), NOW()),
('events.invitations.send', '{"fr":"Envoyer invitations","en":"Send invitations"}'::jsonb, 'events', NULL, NOW(), NOW()),
('events.list', '{"fr":"Lister événements","en":"List events"}'::jsonb, 'events', NULL, NOW(), NOW()),
('events.manage', '{"fr":"Gérer événements","en":"Manage events"}'::jsonb, 'events', NULL, NOW(), NOW()),
('events.publish', '{"fr":"Publier événement","en":"Publish event"}'::jsonb, 'events', NULL, NOW(), NOW()),
('events.read', '{"fr":"Lire événement","en":"Read event"}'::jsonb, 'events', NULL, NOW(), NOW()),
('events.stats.read', '{"fr":"Stats événements","en":"Event stats"}'::jsonb, 'events', NULL, NOW(), NOW()),
('events.update', '{"fr":"Modifier événement","en":"Update event"}'::jsonb, 'events', NULL, NOW(), NOW()),
('guests.checkin', '{"fr":"Check-in invités","en":"Guest check-in"}'::jsonb, 'guests', NULL, NOW(), NOW()),
('guests.create', '{"fr":"Créer invité","en":"Create guest"}'::jsonb, 'guests', NULL, NOW(), NOW()),
('guests.delete', '{"fr":"Supprimer invité","en":"Delete guest"}'::jsonb, 'guests', NULL, NOW(), NOW()),
('guests.export', '{"fr":"Exporter invités","en":"Export guests"}'::jsonb, 'guests', NULL, NOW(), NOW()),
('guests.import', '{"fr":"Importer invités","en":"Import guests"}'::jsonb, 'guests', NULL, NOW(), NOW()),
('guests.read', '{"fr":"Lire invité","en":"Read guest"}'::jsonb, 'guests', NULL, NOW(), NOW()),
('guests.stats.read', '{"fr":"Stats invités","en":"Guest stats"}'::jsonb, 'guests', NULL, NOW(), NOW()),
('guests.update', '{"fr":"Modifier invité","en":"Update guest"}'::jsonb, 'guests', NULL, NOW(), NOW()),
('invoices.create', '{"fr":"Créer invoice","en":"Create invoice"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('invoices.read', '{"fr":"Lire invoice","en":"Read invoice"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('manage_events', '{"fr":"manage_events","en":"manage_events"}'::jsonb, 'manage_events', NULL, NOW(), NOW()),
('marketplace.design', '{"fr":"Design marketplace","en":"Marketplace design"}'::jsonb, 'marketplace', NULL, NOW(), NOW()),
('marketplace.designer.read', '{"fr":"Marketplace designer lire","en":"Designer marketplace read"}'::jsonb, 'marketplace', NULL, NOW(), NOW()),
('marketplace.designer.upload', '{"fr":"Marketplace designer upload","en":"Designer marketplace upload"}'::jsonb, 'marketplace', NULL, NOW(), NOW()),
('marketplace.designers.create', '{"fr":"Créer designer","en":"Create designer"}'::jsonb, 'marketplace', NULL, NOW(), NOW()),
('marketplace.designers.read', '{"fr":"Lire designer","en":"Read designer"}'::jsonb, 'marketplace', NULL, NOW(), NOW()),
('marketplace.designers.update', '{"fr":"Modifier designer","en":"Update designer"}'::jsonb, 'marketplace', NULL, NOW(), NOW()),
('marketplace.purchase', '{"fr":"Acheter template","en":"Purchase template"}'::jsonb, 'marketplace', NULL, NOW(), NOW()),
('marketplace.purchases.read', '{"fr":"Lire achats","en":"Read purchases"}'::jsonb, 'marketplace', NULL, NOW(), NOW()),
('marketplace.read', '{"fr":"Lire marketplace","en":"Read marketplace"}'::jsonb, 'marketplace', NULL, NOW(), NOW()),
('marketplace.reviews.create', '{"fr":"Créer review","en":"Create review"}'::jsonb, 'marketplace', NULL, NOW(), NOW()),
('marketplace.reviews.read', '{"fr":"Lire reviews","en":"Read reviews"}'::jsonb, 'marketplace', NULL, NOW(), NOW()),
('marketplace.stats.read', '{"fr":"Stats marketplace","en":"Marketplace stats"}'::jsonb, 'marketplace', NULL, NOW(), NOW()),
('marketplace.templates.create', '{"fr":"Créer template marketplace","en":"Create marketplace template"}'::jsonb, 'marketplace', NULL, NOW(), NOW()),
('marketplace.templates.purchase', '{"fr":"marketplace.templates.purchase","en":"marketplace.templates.purchase"}'::jsonb, 'marketplace', NULL, NOW(), NOW()),
('marketplace.templates.read', '{"fr":"Lire template marketplace","en":"Read marketplace template"}'::jsonb, 'marketplace', NULL, NOW(), NOW()),
('marketplace.templates.update', '{"fr":"Modifier template marketplace","en":"Update marketplace template"}'::jsonb, 'marketplace', NULL, NOW(), NOW()),
('menus.assign_permissions', '{"fr":"menus.assign_permissions","en":"menus.assign_permissions"}'::jsonb, 'menus', NULL, NOW(), NOW()),
('menus.create', '{"fr":"menus.create","en":"menus.create"}'::jsonb, 'menus', NULL, NOW(), NOW()),
('menus.delete', '{"fr":"menus.delete","en":"menus.delete"}'::jsonb, 'menus', NULL, NOW(), NOW()),
('menus.manage', '{"fr":"menus.manage","en":"menus.manage"}'::jsonb, 'menus', NULL, NOW(), NOW()),
('menus.read', '{"fr":"menus.read","en":"menus.read"}'::jsonb, 'menus', NULL, NOW(), NOW()),
('menus.update', '{"fr":"menus.update","en":"menus.update"}'::jsonb, 'menus', NULL, NOW(), NOW()),
('menus.view_stats', '{"fr":"menus.view_stats","en":"menus.view_stats"}'::jsonb, 'menus', NULL, NOW(), NOW()),
('notifications.bulk.mixed', '{"fr":"Bulk mixed","en":"Bulk mixed"}'::jsonb, 'notifications', NULL, NOW(), NOW()),
('notifications.designer.send', '{"fr":"Designer notif","en":"Designer notif"}'::jsonb, 'notifications', NULL, NOW(), NOW()),
('notifications.email.bulk', '{"fr":"Bulk email","en":"Bulk email"}'::jsonb, 'notifications', NULL, NOW(), NOW()),
('notifications.email.queue', '{"fr":"Queue email","en":"Email queue"}'::jsonb, 'notifications', NULL, NOW(), NOW()),
('notifications.email.send', '{"fr":"Envoyer email","en":"Send email"}'::jsonb, 'notifications', NULL, NOW(), NOW()),
('notifications.event-confirmation.send', '{"fr":"Event confirmation notif","en":"Event confirmation notif"}'::jsonb, 'notifications', NULL, NOW(), NOW()),
('notifications.jobs.cancel', '{"fr":"Annuler jobs notif","en":"Cancel notif jobs"}'::jsonb, 'notifications', NULL, NOW(), NOW()),
('notifications.jobs.read', '{"fr":"Lire jobs notif","en":"Read notif jobs"}'::jsonb, 'notifications', NULL, NOW(), NOW()),
('notifications.organizer.send', '{"fr":"Organizer notif","en":"Organizer notif"}'::jsonb, 'notifications', NULL, NOW(), NOW()),
('notifications.sms.bulk', '{"fr":"Bulk sms","en":"Bulk sms"}'::jsonb, 'notifications', NULL, NOW(), NOW()),
('notifications.sms.queue', '{"fr":"Queue sms","en":"SMS queue"}'::jsonb, 'notifications', NULL, NOW(), NOW()),
('notifications.sms.send', '{"fr":"Envoyer sms","en":"Send sms"}'::jsonb, 'notifications', NULL, NOW(), NOW()),
('notifications.stats.read', '{"fr":"Stats notif","en":"Notif stats"}'::jsonb, 'notifications', NULL, NOW(), NOW()),
('notifications.welcome.send', '{"fr":"Welcome notif","en":"Welcome notif"}'::jsonb, 'notifications', NULL, NOW(), NOW()),
('otp.manage', '{"fr":"otp.manage","en":"otp.manage"}'::jsonb, 'otp', NULL, NOW(), NOW()),
('otp.read', '{"fr":"otp.read","en":"otp.read"}'::jsonb, 'otp', NULL, NOW(), NOW()),
('otp.stats', '{"fr":"otp.stats","en":"otp.stats"}'::jsonb, 'otp', NULL, NOW(), NOW()),
('payment-methods.create', '{"fr":"Créer moyen paiement","en":"Create payment method"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payment-methods.delete', '{"fr":"Supprimer moyen paiement","en":"Delete payment method"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payment-methods.read', '{"fr":"Lire moyen paiement","en":"Read payment method"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payment-methods.update', '{"fr":"Modifier moyen paiement","en":"Update payment method"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payments.cancel', '{"fr":"Annuler paiement","en":"Cancel payment"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payments.create', '{"fr":"Créer paiement","en":"Create payment"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payments.customers.create', '{"fr":"Create customer","en":"Create customer"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payments.customers.read', '{"fr":"Read customer","en":"Read customer"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payments.invoices.create', '{"fr":"Créer facture","en":"Create invoice"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payments.invoices.read', '{"fr":"Lire facture","en":"Read invoice"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payments.payment-methods.create', '{"fr":"Create payment method","en":"Create payment method"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payments.payment-methods.read', '{"fr":"Read payment method","en":"Read payment method"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payments.paypal.capture', '{"fr":"PayPal capture","en":"PayPal capture"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payments.paypal.create', '{"fr":"PayPal create","en":"PayPal create"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payments.read', '{"fr":"Lire paiement","en":"Read payment"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payments.refunds.create', '{"fr":"Créer remboursement","en":"Create refund"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payments.refunds.read', '{"fr":"Lire remboursements","en":"Read refunds"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payments.stats.read', '{"fr":"Stats paiements","en":"Payment stats"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payments.stripe.create', '{"fr":"Stripe create","en":"Stripe create"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('payments.update', '{"fr":"Modifier paiement","en":"Update payment"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('people.create', '{"fr":"people.create","en":"people.create"}'::jsonb, 'people', NULL, NOW(), NOW()),
('people.delete', '{"fr":"people.delete","en":"people.delete"}'::jsonb, 'people', NULL, NOW(), NOW()),
('people.list', '{"fr":"people.list","en":"people.list"}'::jsonb, 'people', NULL, NOW(), NOW()),
('people.read', '{"fr":"people.read","en":"people.read"}'::jsonb, 'people', NULL, NOW(), NOW()),
('people.stats', '{"fr":"people.stats","en":"people.stats"}'::jsonb, 'people', NULL, NOW(), NOW()),
('people.update', '{"fr":"people.update","en":"people.update"}'::jsonb, 'people', NULL, NOW(), NOW()),
('permissions.create', '{"fr":"Créer permission","en":"Create permission"}'::jsonb, 'permissions', NULL, NOW(), NOW()),
('permissions.delete', '{"fr":"Supprimer permission","en":"Delete permission"}'::jsonb, 'permissions', NULL, NOW(), NOW()),
('permissions.read', '{"fr":"Lire permission","en":"Read permission"}'::jsonb, 'permissions', NULL, NOW(), NOW()),
('permissions.update', '{"fr":"Modifier permission","en":"Update permission"}'::jsonb, 'permissions', NULL, NOW(), NOW()),
('permissions.verify', '{"fr":"Vérifier permission","en":"Verify permission"}'::jsonb, 'permissions', NULL, NOW(), NOW()),
('permissions.view_stats', '{"fr":"Stats permissions","en":"Permission stats"}'::jsonb, 'permissions', NULL, NOW(), NOW()),
('refunds.create', '{"fr":"Créer refund","en":"Create refund"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('refunds.read', '{"fr":"Lire refunds","en":"Read refunds"}'::jsonb, 'payments', NULL, NOW(), NOW()),
('roles.assign_permissions', '{"fr":"Assigner permissions","en":"Assign permissions"}'::jsonb, 'roles', NULL, NOW(), NOW()),
('roles.create', '{"fr":"Créer rôle","en":"Create role"}'::jsonb, 'roles', NULL, NOW(), NOW()),
('roles.delete', '{"fr":"Supprimer rôle","en":"Delete role"}'::jsonb, 'roles', NULL, NOW(), NOW()),
('roles.read', '{"fr":"Lire rôle","en":"Read role"}'::jsonb, 'roles', NULL, NOW(), NOW()),
('roles.update', '{"fr":"Modifier rôle","en":"Update role"}'::jsonb, 'roles', NULL, NOW(), NOW()),
('roles.verify', '{"fr":"Vérifier rôle","en":"Verify role"}'::jsonb, 'roles', NULL, NOW(), NOW()),
('roles.view_stats', '{"fr":"Stats rôles","en":"Role stats"}'::jsonb, 'roles', NULL, NOW(), NOW()),
('scans.devices.create', '{"fr":"Créer device scan","en":"Create scan device"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.devices.read', '{"fr":"Lire device scan","en":"Read scan device"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.fraud.analyze', '{"fr":"Analyse fraude","en":"Fraud analyze"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.fraud.read', '{"fr":"Lire fraude","en":"Read fraud"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.history.read', '{"fr":"Lire historique scans","en":"Read scan history"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.offline.cleanup', '{"fr":"Cleanup offline","en":"Offline cleanup"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.offline.read', '{"fr":"Lire offline","en":"Read offline"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.offline.sync', '{"fr":"Sync offline","en":"Offline sync"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.operators.create', '{"fr":"Créer opérateur scan","en":"Create scan operator"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.operators.read', '{"fr":"Lire opérateur scan","en":"Read scan operator"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.qr.batch', '{"fr":"Batch QR","en":"Batch QR"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.qr.decode', '{"fr":"Décoder QR","en":"Decode QR"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.qr.generate', '{"fr":"Générer QR","en":"Generate QR"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.qr.test', '{"fr":"Test QR","en":"Test QR"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.reports.generate', '{"fr":"Générer rapport","en":"Generate report"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.sessions.create', '{"fr":"Créer session scan","en":"Create scan session"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.sessions.read', '{"fr":"Lire session scan","en":"Read scan session"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.sessions.update', '{"fr":"Modifier session scan","en":"Update scan session"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.stats.read', '{"fr":"Stats scans","en":"Scan stats"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.validate', '{"fr":"Valider scan","en":"Validate scan"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('scans.validate.offline', '{"fr":"Valider scan offline","en":"Validate scan offline"}'::jsonb, 'scans', NULL, NOW(), NOW()),
('sessions.cleanup', '{"fr":"sessions.cleanup","en":"sessions.cleanup"}'::jsonb, 'sessions', NULL, NOW(), NOW()),
('sessions.manage', '{"fr":"sessions.manage","en":"sessions.manage"}'::jsonb, 'sessions', NULL, NOW(), NOW()),
('sessions.monitor', '{"fr":"sessions.monitor","en":"sessions.monitor"}'::jsonb, 'sessions', NULL, NOW(), NOW()),
('sessions.read', '{"fr":"sessions.read","en":"sessions.read"}'::jsonb, 'sessions', NULL, NOW(), NOW()),
('sessions.revoke', '{"fr":"sessions.revoke","en":"sessions.revoke"}'::jsonb, 'sessions', NULL, NOW(), NOW()),
('templates.analytics', '{"fr":"Stats templates","en":"Template analytics"}'::jsonb, 'templates', NULL, NOW(), NOW()),
('templates.design', '{"fr":"Designer template","en":"Design template"}'::jsonb, 'templates', NULL, NOW(), NOW()),
('templates.publish', '{"fr":"Publier template","en":"Publish template"}'::jsonb, 'templates', NULL, NOW(), NOW()),
('templates.sell', '{"fr":"Vendre template","en":"Sell template"}'::jsonb, 'templates', NULL, NOW(), NOW()),
('tickets.batch.create', '{"fr":"Batch tickets","en":"Batch tickets"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.create', '{"fr":"Créer ticket","en":"Create ticket"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.delete', '{"fr":"Supprimer ticket","en":"Delete ticket"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.full.batch', '{"fr":"Batch complet","en":"Full batch"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.generate', '{"fr":"Générer ticket","en":"Generate ticket"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.jobs.cancel', '{"fr":"Annuler job","en":"Cancel job"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.jobs.create', '{"fr":"Jobs tickets","en":"Ticket jobs"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.jobs.process', '{"fr":"Process jobs","en":"Process jobs"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.jobs.read', '{"fr":"Lire jobs","en":"Read jobs"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.pdf.batch', '{"fr":"PDF batch","en":"Batch PDF"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.pdf.create', '{"fr":"PDF ticket","en":"Ticket PDF"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.process', '{"fr":"Traiter ticket","en":"Process ticket"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.read', '{"fr":"Lire ticket","en":"Read ticket"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.stats.read', '{"fr":"Stats tickets","en":"Ticket stats"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.templates.create', '{"fr":"Créer template ticket","en":"Create ticket template"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.templates.delete', '{"fr":"Supprimer template ticket","en":"Delete ticket template"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.templates.read', '{"fr":"Lire template ticket","en":"Read ticket template"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.templates.update', '{"fr":"Modifier template ticket","en":"Update ticket template"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.templates.validate', '{"fr":"Valider template ticket","en":"Validate ticket template"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.types.create', '{"fr":"Créer type ticket","en":"Create ticket type"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.types.delete', '{"fr":"Supprimer type ticket","en":"Delete ticket type"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.types.read', '{"fr":"Lire type ticket","en":"Read ticket type"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.types.update', '{"fr":"Modifier type ticket","en":"Update ticket type"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.update', '{"fr":"Modifier ticket","en":"Update ticket"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('tickets.validate', '{"fr":"Valider ticket","en":"Validate ticket"}'::jsonb, 'tickets', NULL, NOW(), NOW()),
('users.create', '{"fr":"users.create","en":"users.create"}'::jsonb, 'users', NULL, NOW(), NOW()),
('users.delete', '{"fr":"users.delete","en":"users.delete"}'::jsonb, 'users', NULL, NOW(), NOW()),
('users.list', '{"fr":"users.list","en":"users.list"}'::jsonb, 'users', NULL, NOW(), NOW()),
('users.read', '{"fr":"Lire profil","en":"Read profile"}'::jsonb, 'users', NULL, NOW(), NOW()),
('users.stats', '{"fr":"users.stats","en":"users.stats"}'::jsonb, 'users', NULL, NOW(), NOW()),
('users.update', '{"fr":"Modifier profil","en":"Update profile"}'::jsonb, 'users', NULL, NOW(), NOW());
